const img = (file) => `/photos/${file}`;

export const cities = [
  {
    id: "london",
    name: "London",
    clusters: ["Modern British", "Indian", "Middle Eastern", "Japanese", "Bakery", "Pub food"],
  },
  {
    id: "bristol",
    name: "Bristol",
    clusters: ["Independent restaurants", "Natural wine + food", "Bakeries", "Seafood", "Experimental"],
  },
  {
    id: "leeds",
    name: "Leeds",
    clusters: ["Yorkshire classics", "South Asian", "Modern British", "Independent pubs"],
  },
  {
    id: "manchester",
    name: "Manchester",
    clusters: ["Northern comfort", "Chinese", "Pakistani", "Indian", "Modern dining"],
  },
  {
    id: "cornwall",
    name: "Cornwall",
    clusters: ["Seafood", "Pasties", "Coastal cafés", "Farm-to-table"],
  },
];

export const dimensions = [
  { key: "sensory", label: "Sensory intensity", copy: "How vividly diners describe taste, texture, aroma and technique." },
  { key: "distinctiveness", label: "Distinctiveness", copy: "Unusual combinations, rare ingredients, heritage recipes." },
  { key: "concentration", label: "Dish concentration", copy: "Independent diners naming the same dish, again and again." },
  { key: "recall", label: "Emotional recall", copy: "Language that the food stayed with them after they left." },
  { key: "returnIntent", label: "Return intent", copy: "Evidence they would go back — or already did." },
  { key: "velocity", label: "Conversation velocity", copy: "Meaningful food mentions accelerating, not just volume." },
];

export const classics = [
  {
    id: "roast",
    name: "Sunday Roast",
    kicker: "British Classics",
    line: "A roast personality, not a league table.",
    traits: ["Crunchy exterior / fluffy centre", "Tall, airy Yorkshire pudding", "Glossy, reduced gravy"],
  },
  {
    id: "pie",
    name: "Pie Index",
    kicker: "Pastry intelligence",
    line: "Filling-to-pastry ratio, gravy, and whether it is traditional or experimental.",
    traits: ["Pastry quality", "Meat tenderness", "Gravy depth"],
  },
  {
    id: "fish",
    name: "Fish & Chips",
    kicker: "Coastal index",
    line: "Batter, freshness, and the salt-and-vinegar balance people actually remember.",
    traits: ["Batter crispness", "Fish freshness", "Chip texture"],
  },
  {
    id: "english",
    name: "Full English",
    kicker: "Breakfast memory",
    line: "Sausage, bacon, eggs and the regional variations that make a plate specific.",
    traits: ["Sausage quality", "Egg cookery", "Hash browns & bread"],
  },
  {
    id: "pub",
    name: "Pub Food",
    kicker: "Counter classics",
    line: "Scotch eggs, rarebit, ploughman’s — the dishes locals order without looking.",
    traits: ["Scotch egg", "Welsh rarebit", "Sausage & mash"],
  },
  {
    id: "curry",
    name: "Curry Index",
    kicker: "Heat & aroma",
    line: "Spice complexity, char, sauce depth and whether the tandoor is doing real work.",
    traits: ["Spice complexity", "Char", "Regional authenticity"],
  },
];

export const prompts = [
  "Where should I eat in Manchester tonight if I want something punchy, non-pretentious and unforgettable under £40?",
  "Where can I get the best pie within reach of Leeds?",
  "Find me something spicy and smoky tonight in Manchester.",
  "I want somewhere worth driving for in Cornwall.",
  "What’s the dish everyone is secretly obsessed with in Bristol?",
  "Show me places under £30 that locals keep returning to.",
  "Find me an old-school British pub with exceptional food.",
  "I want somewhere romantic but not formal in London.",
];

export const venues = [
  {
    id: "herdwick",
    name: "The Herdwick",
    city: "Leeds",
    area: "Kirkstall",
    type: "Independent Yorkshire pub",
    cuisine: "British",
    priceBand: "££",
    ceiling: 34,
    visibility: 18,
    mti: 94,
    momentum: 86,
    hiddenGem: true,
    journey: false,
    classic: "pie",
    styles: ["informal", "traditional", "non-pretentious"],
    tastes: ["rich", "gamey", "comforting", "peppery", "pie"],
    image: img("herdwick.jpg"),
    blurb: "A low-ceilinged pub where fourteen independent diners name the same pie. Visibility is quiet. Memory is not.",
    dish: {
      name: "Herdwick hogget pie",
      protein: "Hogget",
      method: "Slow-cooked",
      sauce: "Deep pepper gravy",
      flavours: ["Rich", "Gamey", "Peppery"],
      textures: ["Crisp pastry", "Tender filling"],
      mentions: 14,
      confidence: "High",
    },
    radar: { sensory: 93, distinctiveness: 90, concentration: 96, recall: 92, returnIntent: 88, velocity: 81 },
    series: [8, 10, 13, 21, 34],
    sensory: ["Rich", "Gamey", "Deep gravy", "Crisp pastry", "Slow-cooked", "Peppery"],
    quotes: [
      { text: "Don’t leave without ordering the lamb pie.", signal: "Dish concentration" },
      { text: "We came back the following week just for the pastry.", signal: "Return intent" },
      { text: "I kept thinking about the gravy on the train home.", signal: "Emotional recall" },
    ],
    personality: { Pastry: "Short, shattering, not thick", Filling: "Hogget, not generic lamb", Gravy: "Peppery, reduced, glossy" },
  },
  {
    id: "smoke-rafter",
    name: "Smoke & Rafter",
    city: "Manchester",
    area: "Ancoats",
    type: "Chef’s counter",
    cuisine: "Modern British",
    priceBand: "££",
    ceiling: 38,
    visibility: 41,
    mti: 91,
    momentum: 88,
    hiddenGem: false,
    journey: false,
    classic: null,
    styles: ["informal", "experimental", "non-pretentious"],
    tastes: ["smoky", "spicy", "fermented", "punchy", "salty"],
    image: img("smoke.jpg"),
    blurb: "Smoked fish and a fermented chilli sauce that reviewers describe with unusual precision — and unusually often.",
    dish: {
      name: "Smoked mackerel, fermented chilli",
      protein: "Mackerel",
      method: "Cold-smoked",
      sauce: "Fermented chilli",
      flavours: ["Smoky", "Salty", "Fermented", "Spicy"],
      textures: ["Silky fish", "Punchy heat"],
      mentions: 11,
      confidence: "High",
    },
    radar: { sensory: 95, distinctiveness: 89, concentration: 84, recall: 90, returnIntent: 82, velocity: 91 },
    series: [6, 9, 14, 22, 31],
    sensory: ["Smoky", "Salty", "Fermented", "Spicy", "Oily", "Bright"],
    quotes: [
      { text: "Still thinking about the chilli on the mackerel.", signal: "Emotional recall" },
      { text: "Punchy without performing. I’d go back just for that plate.", signal: "Return intent" },
    ],
  },
  {
    id: "glossy-gravy",
    name: "The Glossy Gravy",
    city: "Leeds",
    area: "Chapel Allerton",
    type: "Sunday house",
    cuisine: "British classics",
    priceBand: "££",
    ceiling: 32,
    visibility: 36,
    mti: 89,
    momentum: 64,
    hiddenGem: false,
    journey: true,
    classic: "roast",
    styles: ["traditional", "informal", "romantic"],
    tastes: ["rich", "comforting", "crispy", "savoury", "roast"],
    image: img("roast.jpg"),
    blurb: "Not ‘best roast’. A roast with a personality: goose-fat potatoes, a pudding with height, gravy you can see through.",
    dish: {
      name: "Beef roast, goose-fat potatoes",
      protein: "Beef",
      method: "Roasted",
      sauce: "Reduced meat gravy",
      flavours: ["Meaty", "Savoury", "Deep"],
      textures: ["Crunchy potato", "Fluffy centre", "Airy pudding"],
      mentions: 17,
      confidence: "High",
    },
    radar: { sensory: 90, distinctiveness: 74, concentration: 92, recall: 86, returnIntent: 91, velocity: 58 },
    series: [18, 19, 17, 22, 24],
    sensory: ["Crunchy", "Fluffy", "Glossy", "Meaty", "Airy", "Rich"],
    quotes: [
      { text: "Potatoes with a glass-like edge and a cloud inside.", signal: "Sensory intensity" },
      { text: "Worth the drive from York for the gravy alone.", signal: "Worth the journey" },
    ],
    personality: { Potatoes: "Goose-fat, glassy edges", Pudding: "Tall, crisp, not doughy", Gravy: "Glossy, thick, meaty" },
  },
  {
    id: "harbour-line",
    name: "Harbour Line",
    city: "Cornwall",
    area: "Port Isaac",
    type: "Coastal restaurant",
    cuisine: "Seafood",
    priceBand: "£££",
    ceiling: 68,
    visibility: 29,
    mti: 96,
    momentum: 72,
    hiddenGem: true,
    journey: true,
    classic: "fish",
    styles: ["destination", "traditional", "romantic"],
    tastes: ["buttery", "rich", "seafood", "caramelised", "delicate"],
    image: img("turbot.jpg"),
    blurb: "The turbot review that started the thesis: butter-basted edges, a sauce people mention the next morning.",
    dish: {
      name: "Butter-basted turbot",
      protein: "Turbot",
      method: "Butter-basted",
      sauce: "Reduced fish butter",
      flavours: ["Buttery", "Deep", "Marine"],
      textures: ["Caramelised edge", "Silky flesh"],
      mentions: 9,
      confidence: "High",
    },
    radar: { sensory: 98, distinctiveness: 86, concentration: 80, recall: 97, returnIntent: 90, velocity: 70 },
    series: [4, 5, 7, 9, 14],
    sensory: ["Buttery", "Caramelised", "Deep", "Silky", "Saline", "Rich"],
    quotes: [
      { text: "The edges were almost caramelised. I kept thinking about it the next morning.", signal: "Emotional recall" },
      { text: "We travelled from Exeter. Would travel again.", signal: "Worth the journey" },
    ],
  },
  {
    id: "arches",
    name: "Arches Bakery",
    city: "Bristol",
    area: "St Jude’s",
    type: "Railway-arch bakery",
    cuisine: "Bakery",
    priceBand: "£",
    ceiling: 16,
    visibility: 22,
    mti: 87,
    momentum: 90,
    hiddenGem: true,
    journey: false,
    classic: null,
    styles: ["informal", "experimental"],
    tastes: ["fermented", "toasted", "tangy", "buttery", "crispy"],
    image: img("bakery.jpg"),
    blurb: "A morning loaf and a laminated onion tart that Bristol keeps describing in the same three words: toasted, tangy, gone.",
    dish: {
      name: "Onion, miso & thyme tart",
      protein: "Allium",
      method: "Laminated, baked",
      sauce: "Miso butter",
      flavours: ["Toasted", "Umami", "Sweet"],
      textures: ["Flaky", "Caramelised"],
      mentions: 12,
      confidence: "High",
    },
    radar: { sensory: 88, distinctiveness: 91, concentration: 85, recall: 84, returnIntent: 89, velocity: 93 },
    series: [5, 8, 12, 19, 29],
    sensory: ["Toasted", "Flaky", "Umami", "Buttery", "Sweet", "Fermented"],
    quotes: [
      { text: "I’ve been craving the tart since Tuesday.", signal: "Emotional recall" },
      { text: "Locals queue, tourists walk past. That’s the tell.", signal: "Hidden gem" },
    ],
  },
  {
    id: "low-light",
    name: "The Low Light",
    city: "Manchester",
    area: "Rusholme",
    type: "Family grill",
    cuisine: "Pakistani",
    priceBand: "£",
    ceiling: 22,
    visibility: 27,
    mti: 92,
    momentum: 77,
    hiddenGem: true,
    journey: false,
    classic: "curry",
    styles: ["informal", "traditional", "non-pretentious"],
    tastes: ["smoky", "spicy", "charred", "punchy", "aromatic"],
    image: img("curry.jpg"),
    blurb: "Char that tastes like a real tandoor, not a slogan. Heat with aromatics, not just chilli volume.",
    dish: {
      name: "Lamb chops, bone marrow sauce",
      protein: "Lamb",
      method: "Tandoor",
      sauce: "Bone marrow",
      flavours: ["Smoky", "Spiced", "Deep"],
      textures: ["Charred edge", "Juicy"],
      mentions: 13,
      confidence: "High",
    },
    radar: { sensory: 94, distinctiveness: 83, concentration: 88, recall: 86, returnIntent: 93, velocity: 74 },
    series: [11, 12, 14, 18, 23],
    sensory: ["Charred", "Smoky", "Aromatic", "Juicy", "Spicy", "Rich"],
    quotes: [
      { text: "The char is the point. I would go back just for the chops.", signal: "Return intent" },
      { text: "Sauce has depth — clove, not just heat.", signal: "Sensory intensity" },
    ],
    personality: { Heat: "Building, not blunt", Char: "Real tandoor lick", Sauce: "Deep, aromatic" },
  },
  {
    id: "salt-goose",
    name: "Salt & Goose",
    city: "London",
    area: "Bermondsey",
    type: "Modern British dining room",
    cuisine: "Modern British",
    priceBand: "£££",
    ceiling: 72,
    visibility: 63,
    mti: 84,
    momentum: 55,
    hiddenGem: false,
    journey: false,
    classic: null,
    styles: ["romantic", "experimental"],
    tastes: ["umami", "rich", "delicate", "bitter", "buttery"],
    image: img("dining.jpg"),
    blurb: "A room that could coast on atmosphere. The language doesn’t. People write about the goose fat and the bitter leaves.",
    dish: {
      name: "Aged goose, pickled walnut",
      protein: "Goose",
      method: "Roasted",
      sauce: "Walnut and meat jus",
      flavours: ["Rich", "Bitter", "Savoury"],
      textures: ["Crisp skin", "Tender"],
      mentions: 8,
      confidence: "Medium",
    },
    radar: { sensory: 86, distinctiveness: 82, concentration: 71, recall: 80, returnIntent: 74, velocity: 52 },
    series: [12, 11, 13, 12, 15],
    sensory: ["Crisp", "Bitter", "Rich", "Savoury", "Glossy"],
    quotes: [
      { text: "Romantic without the stiff service. The goose is the reason.", signal: "Distinctiveness" },
    ],
  },
  {
    id: "plough-counter",
    name: "The Plough Counter",
    city: "Cornwall",
    area: "Padstow hinterland",
    type: "Farm shop counter",
    cuisine: "Coastal British",
    priceBand: "£",
    ceiling: 14,
    visibility: 11,
    mti: 88,
    momentum: 69,
    hiddenGem: true,
    journey: true,
    classic: "pub",
    styles: ["informal", "traditional", "destination"],
    tastes: ["buttery", "savoury", "crispy", "comforting", "pastry"],
    image: img("bowl.jpg"),
    blurb: "Eleven mentions online. Almost all of them are about the same pasty, and almost all of them sound hungry afterwards.",
    dish: {
      name: "Skirt steak & swede pasty",
      protein: "Skirt",
      method: "Baked",
      sauce: "Pepper gravy on the side",
      flavours: ["Peppery", "Savoury", "Sweet swede"],
      textures: ["Flaky crimp", "Juicy filling"],
      mentions: 11,
      confidence: "High",
    },
    radar: { sensory: 84, distinctiveness: 88, concentration: 93, recall: 85, returnIntent: 80, velocity: 66 },
    series: [3, 4, 4, 7, 11],
    sensory: ["Flaky", "Peppery", "Juicy", "Buttery", "Sweet"],
    quotes: [
      { text: "Made a special trip off the A30. The crimp is the whole story.", signal: "Worth the journey" },
    ],
  },
  {
    id: "rarebit",
    name: "Rarebit Room",
    city: "Bristol",
    area: "Southville",
    type: "Old-school pub",
    cuisine: "Pub food",
    priceBand: "££",
    ceiling: 28,
    visibility: 33,
    mti: 86,
    momentum: 61,
    hiddenGem: false,
    journey: false,
    classic: "pub",
    styles: ["informal", "traditional", "non-pretentious"],
    tastes: ["rich", "savoury", "tangy", "comforting", "pub"],
    image: img("pub.jpg"),
    blurb: "Ale rarebit with a proper burnish. Reviewers skip the interior and write about the mustard and the toast.",
    dish: {
      name: "Ale rarebit, mustard burnish",
      protein: "Cheese",
      method: "Grilled",
      sauce: "Ale and mustard",
      flavours: ["Tangy", "Savoury", "Malty"],
      textures: ["Blistered top", "Yielding toast"],
      mentions: 10,
      confidence: "High",
    },
    radar: { sensory: 82, distinctiveness: 70, concentration: 89, recall: 83, returnIntent: 88, velocity: 57 },
    series: [9, 10, 10, 12, 13],
    sensory: ["Tangy", "Blistered", "Malty", "Rich", "Sharp"],
    quotes: [
      { text: "Best thing I ate this month was a piece of toast. That is the compliment.", signal: "Emotional recall" },
    ],
    personality: { Rarebit: "Mustard-forward, blistered", Toast: "Thick, not soggy", Ale: "Present, not perfume" },
  },
  {
    id: "station-pie",
    name: "Station Pie",
    city: "Leeds",
    area: "Holbeck",
    type: "Pie shop",
    cuisine: "British",
    priceBand: "£",
    ceiling: 12,
    visibility: 19,
    mti: 85,
    momentum: 74,
    hiddenGem: true,
    journey: false,
    classic: "pie",
    styles: ["informal", "traditional", "non-pretentious"],
    tastes: ["rich", "comforting", "savoury", "pie", "peppery"],
    image: img("pie.jpg"),
    blurb: "Steak and ale with a filling-to-pastry ratio people measure in sentences. Under £12, and they still write essays.",
    dish: {
      name: "Steak & ale pie",
      protein: "Steak",
      method: "Braised",
      sauce: "Ale gravy",
      flavours: ["Malty", "Peppery", "Deep"],
      textures: ["Tender beef", "Thin, crisp lid"],
      mentions: 16,
      confidence: "High",
    },
    radar: { sensory: 80, distinctiveness: 68, concentration: 95, recall: 81, returnIntent: 90, velocity: 76 },
    series: [7, 9, 11, 16, 20],
    sensory: ["Tender", "Malty", "Crisp", "Peppery", "Rich"],
    quotes: [
      { text: "The pastry is a lid, not a coffin. I go back weekly.", signal: "Return intent" },
    ],
    personality: { Pastry: "Thin, crisp lid", Filling: "More beef than sauce", Gravy: "Ale, pepper, gloss" },
  },
  {
    id: "chip-chapel",
    name: "Chip Chapel",
    city: "Cornwall",
    area: "St Ives",
    type: "Harbour chippy",
    cuisine: "Fish & chips",
    priceBand: "£",
    ceiling: 18,
    visibility: 48,
    mti: 83,
    momentum: 49,
    hiddenGem: false,
    journey: true,
    classic: "fish",
    styles: ["informal", "traditional", "destination"],
    tastes: ["crispy", "salty", "seafood", "comforting"],
    image: img("chips.jpg"),
    blurb: "Batter that shatters, fish that tastes of that morning, chips with a floury centre. Grease is controlled, not absent.",
    dish: {
      name: "Hake, beef-dripping chips",
      protein: "Hake",
      method: "Fried",
      sauce: "Malt vinegar",
      flavours: ["Saline", "Malty", "Clean"],
      textures: ["Shatter batter", "Floury chip"],
      mentions: 15,
      confidence: "High",
    },
    radar: { sensory: 86, distinctiveness: 64, concentration: 90, recall: 78, returnIntent: 84, velocity: 44 },
    series: [20, 18, 21, 19, 22],
    sensory: ["Crisp", "Saline", "Floury", "Clean", "Hot"],
    quotes: [
      { text: "Batter like glass. Worth the train from Plymouth.", signal: "Worth the journey" },
    ],
    personality: { Batter: "Shatter, not soggy", Fish: "Hake, sweet, fresh", Chips: "Floury centre, crisp edge" },
  },
  {
    id: "dawn-plate",
    name: "Dawn Plate",
    city: "London",
    area: "Hackney",
    type: "Breakfast room",
    cuisine: "Full English",
    priceBand: "££",
    ceiling: 24,
    visibility: 44,
    mti: 81,
    momentum: 68,
    hiddenGem: false,
    journey: false,
    classic: "english",
    styles: ["informal", "traditional"],
    tastes: ["savoury", "crispy", "rich", "comforting"],
    image: img("breakfast.jpg"),
    blurb: "A full English argued at the level of sausage snap and mushroom juice. Regional, specific, not a hotel buffet.",
    dish: {
      name: "Full English, fennel sausage",
      protein: "Pork",
      method: "Griddled",
      sauce: "Tomato and bone broth beans",
      flavours: ["Fennel", "Savoury", "Sweet-sour"],
      textures: ["Snap casing", "Crisp bacon", "Soft yolk"],
      mentions: 9,
      confidence: "Medium",
    },
    radar: { sensory: 84, distinctiveness: 77, concentration: 73, recall: 79, returnIntent: 82, velocity: 66 },
    series: [6, 7, 8, 11, 14],
    sensory: ["Snap", "Crisp", "Fennel", "Rich", "Soft"],
    quotes: [
      { text: "The sausage is the reason I’d cross the city before noon.", signal: "Return intent" },
    ],
    personality: { Sausage: "Fennel, real snap", Eggs: "Soft yolk, crisp lace", Beans: "Reduced, not tin-sweet" },
  },
  {
    id: "velvet-tandoor",
    name: "Velvet Tandoor",
    city: "Manchester",
    area: "Northern Quarter",
    type: "Regional Indian",
    cuisine: "Indian",
    priceBand: "££",
    ceiling: 36,
    visibility: 52,
    mti: 88,
    momentum: 71,
    hiddenGem: false,
    journey: false,
    classic: "curry",
    styles: ["informal", "romantic"],
    tastes: ["spicy", "aromatic", "smoky", "rich", "punchy"],
    image: img("tandoor.jpg"),
    blurb: "Sauce with body. Heat that opens into cardamom and char, not a single note of chilli.",
    dish: {
      name: "Butter chicken, real tandoor char",
      protein: "Chicken",
      method: "Tandoor then simmered",
      sauce: "Tomato, fenugreek, butter",
      flavours: ["Smoky", "Sweet", "Aromatic"],
      textures: ["Charred pieces", "Velvet sauce"],
      mentions: 12,
      confidence: "High",
    },
    radar: { sensory: 89, distinctiveness: 76, concentration: 87, recall: 84, returnIntent: 85, velocity: 69 },
    series: [10, 12, 13, 16, 19],
    sensory: ["Smoky", "Velvet", "Aromatic", "Charred", "Rich"],
    quotes: [
      { text: "I don’t care that it’s famous. The fenugreek is correct.", signal: "Distinctiveness" },
    ],
    personality: { Heat: "Warm, rounded", Char: "Visible on the meat", Sauce: "Velvet, not cloying" },
  },
  {
    id: "orchard-inn",
    name: "Orchard Inn",
    city: "Bristol",
    area: "Chew Valley",
    type: "Country inn",
    cuisine: "Modern British",
    priceBand: "£££",
    ceiling: 58,
    visibility: 24,
    mti: 90,
    momentum: 79,
    hiddenGem: true,
    journey: true,
    classic: null,
    styles: ["destination", "romantic", "traditional"],
    tastes: ["earthy", "rich", "gamey", "comforting", "wood-fired"],
    image: img("inn.jpg"),
    blurb: "Diners name the drive. Then they name the wood-fired celeriac. Destination eating, measured in journeys not stars.",
    dish: {
      name: "Wood-fired celeriac, hazelnut",
      protein: "Celeriac",
      method: "Wood-fired",
      sauce: "Brown butter hazelnut",
      flavours: ["Earthy", "Nutty", "Sweet"],
      textures: ["Burnished", "Creamy centre"],
      mentions: 8,
      confidence: "Medium",
    },
    radar: { sensory: 91, distinctiveness: 92, concentration: 78, recall: 93, returnIntent: 86, velocity: 80 },
    series: [3, 4, 6, 9, 13],
    sensory: ["Wood-fired", "Earthy", "Nutty", "Burnished", "Sweet"],
    quotes: [
      { text: "Worth driving for. We came from Bath for the celeriac and stayed for the fire.", signal: "Worth the journey" },
    ],
  },
];

export const digest = {
  issue: "Vol. 04",
  title: "This week’s taste memories",
  date: "Week of 22 September",
  items: [
    { kind: "Emerging dish", venueId: "arches", note: "Sensory mentions of the miso onion tart jumped from 12 to 29 across five weeks." },
    { kind: "British classic", venueId: "herdwick", note: "Fourteen independent reviews. One pie. That is the Pie Index working as intended." },
    { kind: "Hidden gem", venueId: "plough-counter", note: "Taste signal in the high eighties. Online footprint barely registers." },
    { kind: "Worth the journey", venueId: "harbour-line", note: "Journey language — Exeter, Plymouth, ‘next morning’ — clusters around one turbot." },
    { kind: "Signature dish", venueId: "station-pie", note: "Highest cross-reviewer agreement in Leeds this week." },
    { kind: "Rising taste", venueId: "smoke-rafter", note: "Fastest growth in meaningful food sentences, not in follower count." },
  ],
};

export function getVenue(id) {
  return venues.find((v) => v.id === id);
}

export function byCity(city) {
  if (!city || city === "all") return venues;
  return venues.filter((v) => v.city.toLowerCase() === city.toLowerCase());
}
